application: votesup
version: 1
runtime: python
api_version: 1

skip_files: 
- ^(.*/)?\.git.*.

handlers:
- url: /static
  static_dir: static

- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never

- url: /admin/.*
  script: main.py
  login: admin

- url: /tempadmin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
- remote_api: on
